# -*- coding: utf-8 -*-
"""TASK 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jL43i5rlGETHgQg5MuZYP9asFBdRvFU
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# load csv
df = 'sales_data_sample.csv'
try:
    df = pd.read_csv(df, encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv(df, encoding='latin1')

df

# select and rename columns for clarity
df_selected = df[['PRODUCTLINE', 'QUANTITYORDERED', 'PRICEEACH']].copy()
df_selected.columns = ['product', 'quantity', 'price']

# create database in sqlite3 & insert data into DB
conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

cursor.execute('DROP TABLE IF EXISTS sales_data_sample')
cursor.execute('''
CREATE TABLE sales_data_sample (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
)
''')

for _, row in df_selected.iterrows():
    cursor.execute('INSERT INTO sales_data_sample (product, quantity, price) VALUES (?, ?, ?)',
                   (row['product'], int(row['quantity']), float(row['price'])))

conn.commit()

# query total quantity sold and total revenue by product
query = '''
SELECT product, SUM(quantity) as total_qty, SUM(quantity * price) as revenue
FROM sales_data_sample
GROUP BY product
ORDER BY revenue DESC
'''
df_summary = pd.read_sql_query(query, conn)

# print results
print(df_summary)

# plot bar chart for revenue by product
df_summary.plot(kind='bar', x='product', y='revenue', legend=False)
plt.title('Product Revenue Comparison')
plt.xlabel('Product')
plt.ylabel('Revenue')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

conn.close()

